-- EzMsg Initial Database Schema
-- PostgreSQL 16

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For text search

-- Enumerations
CREATE TYPE project_status AS ENUM ('NONE', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'DELETED');
CREATE TYPE participant_status AS ENUM ('NONE', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'COMPLETED', 'BLOCKED_SYSTEM');
CREATE TYPE messaging_channel_type AS ENUM ('NONE', 'TWILIO', 'FACEBOOK', 'MOBILE_APP', 'EMAIL');
CREATE TYPE scheduled_message_status AS ENUM ('PENDING', 'IN_PROGRESS', 'SENT', 'SKIPPED', 'FAILED', 'ABORTED');
CREATE TYPE sms_message_direction AS ENUM ('OUTGOING', 'INCOMING');
CREATE TYPE node_timing_object_type AS ENUM ('TIMING_VARIABLE', 'MESSAGING_NODE', 'MESSAGE_TEMPLATE', 'KEYWORD');
CREATE TYPE variable_type AS ENUM ('STRING', 'INTEGER', 'DECIMAL', 'DATETIME', 'BOOLEAN');
CREATE TYPE variable_source_type AS ENUM ('MANUAL', 'CALCULATED', 'EXTERNAL', 'SYSTEM');
CREATE TYPE user_role AS ENUM ('ADMIN', 'RESEARCHER', 'OPERATOR');

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role user_role NOT NULL DEFAULT 'OPERATOR',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);

-- Available languages
CREATE TABLE available_languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(10) NOT NULL,
    code INT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

-- Seed languages
INSERT INTO available_languages (name, short_name, code) VALUES
    ('English', 'en', 1),
    ('Spanish', 'es', 2);

-- Projects
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uu_id VARCHAR(100) UNIQUE DEFAULT uuid_generate_v4()::text,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status project_status NOT NULL DEFAULT 'ACTIVE',
    initial_triggering_node_id BIGINT, -- FK added after messaging_nodes
    settings JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (user_id, name)
);

CREATE INDEX idx_projects_status ON projects(status);
CREATE INDEX idx_projects_created_at ON projects(created_at);
CREATE INDEX idx_projects_user ON projects(user_id);

-- Project user access (for role-based access)
CREATE TABLE project_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_level VARCHAR(50) NOT NULL DEFAULT 'read', -- read, write, admin
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, user_id)
);

-- Variables
CREATE TABLE variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uu_id VARCHAR(100) UNIQUE DEFAULT uuid_generate_v4()::text,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    type variable_type NOT NULL DEFAULT 'STRING',
    source_type variable_source_type NOT NULL DEFAULT 'MANUAL',
    external_name VARCHAR(255),
    default_value TEXT,
    description TEXT,
    is_automatically_generated BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (project_id, name)
);

CREATE INDEX idx_variables_type ON variables(type);
CREATE INDEX idx_variables_source_type ON variables(source_type);
CREATE INDEX idx_variables_project ON variables(project_id);

-- Participants
CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uu_id VARCHAR(100) UNIQUE DEFAULT uuid_generate_v4()::text,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    channel_type messaging_channel_type NOT NULL DEFAULT 'MOBILE_APP',
    status participant_status NOT NULL DEFAULT 'ACTIVE',
    current_language_id BIGINT NOT NULL REFERENCES available_languages(id) DEFAULT 1,
    phone_number VARCHAR(50),
    phone_number_hash VARCHAR(64),
    external_id VARCHAR(255),
    is_test_participant BOOLEAN NOT NULL DEFAULT FALSE,
    participant_info TEXT,
    fcm_token VARCHAR(500),
    enrolled_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

CREATE INDEX idx_participants_project_status ON participants(project_id, status);
CREATE INDEX idx_participants_phone ON participants(phone_number);
CREATE INDEX idx_participants_external_id ON participants(external_id);
CREATE INDEX idx_participants_fcm ON participants(fcm_token) WHERE fcm_token IS NOT NULL;

-- Participant variable values
CREATE TABLE participant_variable_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES variables(id) ON DELETE CASCADE,
    variable_value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (participant_id, variable_id)
);

CREATE INDEX idx_pvv_participant ON participant_variable_values(participant_id);
CREATE INDEX idx_pvv_variable ON participant_variable_values(variable_id);

-- Message templates
CREATE TABLE message_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL DEFAULT 'STANDARD',
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (project_id, name)
);

CREATE INDEX idx_templates_project ON message_templates(project_id);
CREATE INDEX idx_templates_type ON message_templates(type);

-- Message template texts (i18n)
CREATE TABLE message_template_texts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES message_templates(id) ON DELETE CASCADE,
    language_id BIGINT NOT NULL REFERENCES available_languages(id),
    message_text TEXT,
    media_url VARCHAR(512),
    media_type VARCHAR(50), -- image, gif, video
    quick_replies JSONB DEFAULT '[]', -- Array of {label, value} objects
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (template_id, language_id)
);

CREATE INDEX idx_template_texts_template ON message_template_texts(template_id);

-- Message template variables (join table)
CREATE TABLE message_template_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES message_templates(id) ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES variables(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (template_id, variable_id)
);

-- Timing elements
CREATE TABLE timing_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    offset_direction VARCHAR(10) NOT NULL DEFAULT 'AFTER', -- BEFORE/AFTER
    offset_days INT NOT NULL DEFAULT 0,
    offset_hours INT NOT NULL DEFAULT 0,
    offset_minutes INT NOT NULL DEFAULT 0,
    offset_seconds INT NOT NULL DEFAULT 0,
    overwrite_time BOOLEAN NOT NULL DEFAULT FALSE,
    overwritten_hours INT,
    overwritten_minutes INT,
    time_variable_id BIGINT REFERENCES variables(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (project_id, name)
);

CREATE INDEX idx_timing_project ON timing_elements(project_id);

-- Conditional expressions
CREATE TABLE conditional_expressions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    condition_text TEXT NOT NULL, -- Boolean expression
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (project_id, name)
);

CREATE INDEX idx_conditions_project ON conditional_expressions(project_id);

-- Conditional expression variables
CREATE TABLE conditional_expression_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conditional_expression_id BIGINT NOT NULL REFERENCES conditional_expressions(id) ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES variables(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (conditional_expression_id, variable_id)
);

-- Messaging nodes
CREATE TABLE messaging_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    description TEXT,
    is_terminal_node BOOLEAN NOT NULL DEFAULT FALSE,
    is_entry_node BOOLEAN NOT NULL DEFAULT FALSE,
    exec_commands TEXT,
    conditional_expression_id BIGINT REFERENCES conditional_expressions(id),
    template_id BIGINT REFERENCES message_templates(id),
    timing_element_id BIGINT REFERENCES timing_elements(id),
    node_timing_object_type node_timing_object_type NOT NULL DEFAULT 'MESSAGING_NODE',
    timing_variable_id BIGINT REFERENCES variables(id),
    answered_template_id BIGINT REFERENCES message_templates(id),
    node_order INT DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (project_id, name)
);

CREATE INDEX idx_nodes_project ON messaging_nodes(project_id);
CREATE INDEX idx_nodes_terminal ON messaging_nodes(is_terminal_node) WHERE is_terminal_node = TRUE;
CREATE INDEX idx_nodes_entry ON messaging_nodes(is_entry_node) WHERE is_entry_node = TRUE;

-- Add FK to projects for initial node
ALTER TABLE projects ADD CONSTRAINT fk_projects_initial_node
    FOREIGN KEY (initial_triggering_node_id) REFERENCES messaging_nodes(id);

-- Messaging node edges (graph links)
CREATE TABLE messaging_node_edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_node_id BIGINT NOT NULL REFERENCES messaging_nodes(id) ON DELETE CASCADE,
    child_node_id BIGINT NOT NULL REFERENCES messaging_nodes(id) ON DELETE CASCADE,
    condition_expression_id BIGINT REFERENCES conditional_expressions(id),
    edge_label VARCHAR(255), -- For quick reply routing
    edge_order INT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ,
    UNIQUE (parent_node_id, child_node_id)
);

CREATE INDEX idx_edges_parent ON messaging_node_edges(parent_node_id);
CREATE INDEX idx_edges_child ON messaging_node_edges(child_node_id);

-- Scheduled messages (scheduler work queue)
CREATE TABLE scheduled_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    participant_id BIGINT NOT NULL REFERENCES participants(id),
    messaging_node_id BIGINT REFERENCES messaging_nodes(id),
    template_id BIGINT REFERENCES message_templates(id),
    status scheduled_message_status NOT NULL DEFAULT 'PENDING',
    message_body TEXT,
    media_url VARCHAR(512),
    quick_replies JSONB,
    send_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    direction sms_message_direction NOT NULL DEFAULT 'OUTGOING',
    channel_type messaging_channel_type NOT NULL DEFAULT 'MOBILE_APP',
    external_id VARCHAR(255), -- Provider message SID
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 8,
    last_attempt_at TIMESTAMPTZ,
    last_error_code VARCHAR(50),
    last_error_message TEXT,
    provider_response JSONB,
    idempotency_key VARCHAR(255) UNIQUE,
    locked_at TIMESTAMPTZ,
    locked_by VARCHAR(100),
    lock_token VARCHAR(100),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

-- Critical scheduler indexes
CREATE INDEX idx_scheduled_pending_due ON scheduled_messages(send_at, id)
    WHERE status = 'PENDING';
CREATE INDEX idx_scheduled_participant_status ON scheduled_messages(participant_id, status);
CREATE INDEX idx_scheduled_status ON scheduled_messages(status);
CREATE INDEX idx_scheduled_project ON scheduled_messages(project_id);
CREATE INDEX idx_scheduled_node ON scheduled_messages(messaging_node_id);

-- Incoming messages
CREATE TABLE incoming_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(id),
    participant_id BIGINT REFERENCES participants(id),
    scheduled_message_id BIGINT REFERENCES scheduled_messages(id), -- Reply to which message
    template_id BIGINT REFERENCES message_templates(id),
    channel_type messaging_channel_type NOT NULL,
    from_address VARCHAR(100) NOT NULL,
    to_address VARCHAR(100),
    body TEXT,
    external_id VARCHAR(255),
    quick_reply_value VARCHAR(255), -- If this was a quick reply
    unit_price DECIMAL(10, 6),
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

CREATE INDEX idx_incoming_participant ON incoming_messages(participant_id);
CREATE INDEX idx_incoming_received ON incoming_messages(received_at);
CREATE INDEX idx_incoming_unprocessed ON incoming_messages(processed) WHERE processed = FALSE;

-- SMS Keywords
CREATE TABLE sms_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    language_id BIGINT REFERENCES available_languages(id),
    keyword_action_type VARCHAR(50) NOT NULL, -- TRIGGER_NODE, SET_VARIABLE, OPT_OUT, HELP
    keyword_name VARCHAR(100) NOT NULL,
    keyword_text VARCHAR(255) NOT NULL,
    messaging_node_id BIGINT REFERENCES messaging_nodes(id),
    variable_id BIGINT REFERENCES variables(id),
    variable_value TEXT,
    response_template_id BIGINT REFERENCES message_templates(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    removed_at TIMESTAMPTZ
);

CREATE INDEX idx_keywords_text ON sms_keywords(LOWER(keyword_text));
CREATE INDEX idx_keywords_project ON sms_keywords(project_id);

-- Audit log for important actions
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    old_values JSONB,
    new_values JSONB,
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_user ON audit_logs(user_id);
CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_logs(created_at);

-- Refresh tokens table for token management
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_hash ON refresh_tokens(token_hash);

-- Admin user is seeded by the application on first startup (see backend/app/database/seed_db.py)

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for all tables with updated_at
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.columns
        WHERE column_name = 'updated_at'
        AND table_schema = 'public'
    LOOP
        EXECUTE format('
            CREATE TRIGGER update_%I_updated_at
            BEFORE UPDATE ON %I
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        ', t, t);
    END LOOP;
END;
$$ LANGUAGE plpgsql;
